### ISSUE TITLE
Notifications stopped working?

### ISSUE THREAD

**Issue by jaxxstorm** [manojVivek/social-snitch#6]
I haven't had any pings since early may, everything still working as expected?

**Comment by manojVivek** [comment]
Discovered the notification transmitter crashes completely when there is an error in transmitting a notification. Fixed it and it should be good now.

**Comment by manojVivek** [comment]
Also, noticed that Twitter has removed tweet search access for the free api users. So we need to figure out an alternative for twitter.

**Comment by manojVivek** [comment]
Ref: https://github.com/manojVivek/social-snitch/issues/12
